version = 5.5.0
archive_dir = /etc/letsencrypt/archive/mcp.dev.centaursoftware.com
cert = /etc/letsencrypt/live/mcp.dev.centaursoftware.com/cert.pem
privkey = /etc/letsencrypt/live/mcp.dev.centaursoftware.com/privkey.pem
chain = /etc/letsencrypt/live/mcp.dev.centaursoftware.com/chain.pem
fullchain = /etc/letsencrypt/live/mcp.dev.centaursoftware.com/fullchain.pem
[renewalparams]
account = 2fbc95a374e162055afd49e778da8c57
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
mcp.dev.centaursoftware.com = /var/www/certbot
